# Generated by Django 5.0.6 on 2024-06-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
