# Generated by Django 5.0.6 on 2024-06-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_header_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.header')),
            ],
        ),
    ]
