# Generated by Django 5.0.6 on 2024-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_softskill_skill_hex_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softskill',
            name='skill_hex_color',
            field=models.CharField(max_length=7),
        ),
    ]
