# Generated by Django 5.0.6 on 2024-06-09 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_softskill_skill_hex_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_percentage', models.CharField(max_length=50)),
                ('skill_hex_color', models.CharField(max_length=7)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.header')),
            ],
        ),
    ]
