# Generated by Django 5.0.6 on 2024-06-09 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_hardskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.header')),
            ],
        ),
    ]
