# Generated by Django 5.0.6 on 2024-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
