# Generated by Django 5.0.6 on 2024-06-09 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_experience_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('project_link', models.CharField(max_length=50)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.header')),
            ],
        ),
    ]
