# Generated by Django 5.0.6 on 2024-06-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
