# Generated by Django 5.0.6 on 2024-06-10 15:39

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(null=True, upload_to=portfolio.models.get_file_name),
        ),
    ]
