# Generated by Django 5.0.6 on 2024-06-10 16:03

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_experience_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=portfolio.models.get_file_name)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.header')),
            ],
        ),
    ]
