# Generated by Django 5.0.6 on 2024-06-10 16:31

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_experienceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='header_image',
            field=models.ImageField(null=True, upload_to=portfolio.models.get_file_name),
        ),
    ]
